# Generated by Django 5.0.2 on 2024-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlmacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
