# Generated by Django 5.0.2 on 2024-03-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlmacen', '0005_alter_producto_imagen_productoimagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoUpdateImagen',
        ),
    ]
