# Generated by Django 5.0.2 on 2024-03-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAlmacen', '0006_delete_productoupdateimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_producto', to='AppAlmacen.producto'),
        ),
    ]
